cutting:
  cutting_mode: Slice once every 4 sentences
global:
  use_new_api: false
gpt:
  if_freeze: false
  speed: 1
  temperature: 0.65
  top_k: 15
  top_p: 0.1
inference:
  inference_text_language: 中英混合
minecraft_api_key:
  minecraft_api_key: sk-12345678abcdefgh12345678abcdefgh12345678abcdefgh
mode:
  mode: tts
reference:
  inp_refs: null
  no_reference_mode: false
  reference_audio_language: Chinese
  reference_audio_local: ''
  reference_audio_text: 阿米娅看上去还是这么瘦弱，这个年纪的孩子，个子是不是应该更高一点才对？她到底有没有好好吃饭呢。
  reference_audio_url: https://fs-im-kefu.7moor-fs1.com/ly/4d2c3f00-7d4c-11e5-af15-41bf63ae4ea0/1739002890857/audio.wav
